# Generated by Django 4.1.2 on 2022-11-05 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='profile/avatar.png', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='special_user',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 5, 9, 38, 10, 280174, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
