# Generated by Django 4.1.2 on 2022-11-05 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_useraccount_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 9, 38, 27, 434355, tzinfo=datetime.timezone.utc)),
        ),
    ]
