# Generated by Django 4.1.2 on 2022-11-05 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_alter_useraccount_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='special_user',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
