# Generated by Django 4.1.2 on 2022-11-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_alter_useraccount_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='profile/avatar.png', null=True, upload_to='profile'),
        ),
    ]
