# Generated by Django 4.1.2 on 2022-11-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
