# Generated by Django 4.1.2 on 2022-11-24 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('code', models.CharField(max_length=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('valid_to', models.DateTimeField()),
                ('valid_for', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupon Module',
            },
        ),
    ]
