# Generated by Django 4.1.2 on 2022-10-24 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HitsThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(allow_unicode=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.tags')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tagsModules',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products')),
                ('status', models.CharField(choices=[('puplish', 'Puplish'), ('draft', 'Draft'), ('pending', 'Pending'), ('delete', 'Delete')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hits', models.ManyToManyField(related_name='products_hits', through='products.HitsThrough', to='products.ipaddress')),
                ('tags', models.ManyToManyField(to='products.tags')),
            ],
            options={
                'verbose_name': ('product',),
                'verbose_name_plural': 'productsModule',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='hitsthrough',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ipaddress'),
        ),
        migrations.AddField(
            model_name='hitsthrough',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products'),
        ),
    ]
