# Generated by Django 4.1.2 on 2022-10-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_tags_alter_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
