# Generated by Django 4.1.2 on 2022-11-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='products_hits', through='products.HitsThrough', to='products.ipaddress'),
        ),
    ]
